Update ContractorUI
donnac94/verklegt3-HR24 pull request #76
Opened 2024-12-10 13:44 UTC by HelgaS-24

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

### Checklist

- [ ] I have self-reviewed my own code
- [ ] My code generates no new warnings
- [ ] I have formatted my code
- [ ] I have documented what I feel is necessary

2024-12-10 14:15 UTC, donnac94 requested changes

2024-12-10 14:15 UTC, donnac94 commented on UI_Layer/PropertyUI.py
hverju ertu að breyta hér? 
Þetta heitir PropertyManagment_UI núna ertu að bæta við nýtt submenu ?

2024-12-10 14:40 UTC, HelgaS-24 commented on UI_Layer/PropertyUI.py
ég er bara að reyna að breyta ContractorUI ekki Property

2024-12-11 12:01 UTC, GunnarAndri approved these changes

2024-12-11 12:01 UTC, donnac94 approved these changes

2024-12-11 12:01 UTC, donnac94 commented on UI_Layer/PropertyUI.py
það eru 2 files changed - ContractorUI og PropertyUI

2024-12-11 12:01 UTC, donnac94 commented on UI_Layer/PropertyUI.py
myndi eyða PropertyUI af brancinu þínu og þá er þetta good to go

2024-12-11 12:01 UTC, donnac94 commented on UI_Layer/ContractorUI.py
> +            print(d + "Welcome to the Contractor Menu".center(columns - 2) + d)
Mátt breyta þessu í "Welcome to the Contractor Management Menu"
Svo það sé eins og í Property Management og Employee Management

2024-12-11 12:01 UTC, merged